
<h2>Add a new review</h2>
<p><span style="color: red;">* required field.</span></p>

    <div>
        <span style="float: left; width: 70px;clear: both;">Name:</span> <input type="text" name="name" value="">
        <span class="error" style="color: red;">*</span>
    </div>
    <div style="padding-top: 10px;">
        <span style="float: left; width: 70px;clear: both;">Email:</span> <input type="text" name="email" value="">
        <span class="error" style="color: red;">*</span>
    </div>
    <div style="padding-top: 10px;">
        <span style="float: left; width: 70px;clear: both;">Review:</span> <textarea name="review" rows="5" cols="40"></textarea>
        <span class="error" style="color: red;">*</span>
    </div>
    <div>
        <input type="submit" name="submit_button" value="SUBMIT" id="update_button" class="update_button">
    </div>
